arrays:
   - endpoint: "https://192.168.1.40/api/rest"     # full URL path to the PowerStore API
     globalID: "powerstore-1"                        # unique id of the PowerStore array
     username: "admin"                          # username for connecting to API
     password: "Password123!"                      # password for connecting to API
     skipCertificateValidation: true           # indicates if client side validation of (management)server's certificate can be skipped
     isDefault: true                           # treat current array as a default (would be used by storage classes without arrayID parameter)
     blockProtocol: "iSCSI"                     # what SCSI transport protocol use on node side (FC, ISCSI, NVMeTCP, NVMeFC, None, or auto)
#     nasName: "nas-server"                     # what NAS should be used for NFS volumes
#     nfsAcls: "0777"                           # (Optional) defines permissions - POSIX mode bits or NFSv4 ACLs, to be set on NFS target mount directory.
                                               # NFSv4 ACls are supported for NFSv4 shares on NFSv4 enabled NAS servers only. POSIX ACLs are not supported and only POSIX mode bits are supported for NFSv3 shares.
   - endpoint: "https://192.168.1.45/api/rest"     # full URL path to the PowerStore API
     globalID: "powerstore-2"                        # unique id of the PowerStore array
     username: "admin"                          # username for connecting to API
     password: "Password123!"                      # password for connecting to API
     skipCertificateValidation: true           # indicates if client side validation of (management)server's certificate can be skipped
     isDefault: true                           # treat current array as a default (would be used by storage classes without arrayID parameter)
     blockProtocol: "iSCSI"                     # what SCSI transport protocol use on node side (FC, ISCSI, NVMeTCP, NVMeFC, None, or auto)
#     nasName: "nas-server"                     # what NAS should be used for NFS volumes
#     nfsAcls: "0777"                           # (Optional) defines permissions - POSIX mode bits or NFSv4 ACLs, to be set on NFS target mount directory.
                                
