apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replicated-powerstore-pvc
  namespace: powerstore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: powerstore-replication
