kind: Namespace
apiVersion: v1
metadata:
  name: powerstore
  labels:
    name: powerstore
---    
apiVersion: v1
kind: Secret
metadata:
   name: powerstore-config
   namespace: powerstore
type: Opaque
data:
   config: CONFIG_YAML
