kind: Namespace
apiVersion: v1
metadata:
  name: csi-powerstore
  labels:
    name: csi-powerstore
---    
apiVersion: v1
kind: Secret
metadata:
   name: powerstore-config
   namespace: csi-powerstore
type: Opaque
data:
   config: CONFIG_YAML
