---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename
  tasks:
    - name: "Add {{ ppdm.assets.jt.sql.query.name }}"
      job_template:
        name: "{{ ppdm.assets.jt.sql.query.name }}"
        description: "{{ ppdm.assets.jt.sql.query.description }}"
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "30.0-playbook_get_assets.yml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
          - "{{ ppdm.policy.jt.sql.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          asset_filter: type eq "MICROSOFT_SQL_DATABASE" and protectionStatus eq "UNPROTECTED" and operatingSystem.name eq "Windows"
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.assets.jt.exchange.query.name }}"
      job_template:
        name: "{{ ppdm.assets.jt.exchange.query.name }}"
        description: "{{ ppdm.assets.jt.exchange.query.description }}"
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "30.0-playbook_get_assets.yml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
          - "{{ ppdm.policy.jt.exchange.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          asset_filter: type eq "MICROSOFT_EXCHANGE_DATABASE" and protectionStatus eq "UNPROTECTED" and operatingSystem.name eq "Windows"
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.assets.jt.fs.query.name }}"
      job_template:
        name: "{{ ppdm.assets.jt.fs.query.name }}"
        description: "{{ ppdm.assets.jt.fs.query.description  }}"
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "30.0-playbook_get_assets.yml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
          - "{{ ppdm.policy.jt.fs.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          asset_filter: type eq "FILE_SYSTEM" and protectionStatus eq "UNPROTECTED" and operatingSystem.name eq "Windows"
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.agents.jt.fs.approve.name }}"
      job_template:
        name: "{{ ppdm.agents.jt.fs.approve.name }}"
        description: "{{ ppdm.agents.jt.fs.approve.description }}"
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "100.4_create_whitelistentry_from_addressquery.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
          - "{{ ppdm.policy.jt.fs.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          host_list: launchpad.demo.local
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.agents.jt.sql.approve.name }}"
      job_template:
        name: "{{ ppdm.agents.jt.sql.approve.name }}"
        description: "{{ ppdm.agents.jt.sql.approve.description }}"
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "100.4_create_whitelistentry_from_addressquery.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
          - "{{ ppdm.policy.jt.sql.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          host_list: SQL02.demo.local,SQL01.demo.local
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.agents.jt.exchange.approve.name }}"
      job_template:
        name: "{{ ppdm.agents.jt.exchange.approve.name }}"
        description: "{{ ppdm.agents.jt.exchange.approve.description }}"
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "100.4_create_whitelistentry_from_addressquery.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
          - "{{ ppdm.policy.jt.exchange.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          host_list: exchange1.demo.local,exchange2.demo.local
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Give {{ ppdm.agents.user_1.username }} permissions"
      role:
        user: "{{ ppdm.agents.user_1.username }}"    
        role: execute
        job_templates:
          - "{{ ppdm.policy.jt.sql.name }}"
          - "{{ ppdm.policy.jt.exchange.name }}"
          - "{{ ppdm.policy.jt.fs.name }}"
          - "{{ ppdm.assets.jt.sql.query.name }}"
          - "{{ ppdm.assets.jt.exchange.query.name }}" 
          - "{{ ppdm.assets.jt.fs.query.name }}"
          - "{{ ppdm.agents.jt.exchange.approve.name }}"
          - "{{ ppdm.agents.jt.sql.approve.name }}"
          - "{{ ppdm.agents.jt.fs.approve.name }}"                   