---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename
  tasks:
    - name: "Add {{ ppdm.k8s.jt.namespace.remove.name  }}"
      job_template:
        name: "{{ ppdm.k8s.jt.namespace.remove.name }}"
        description: "{{ ppdm.k8s.jt.namespace.remove.description }}"
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "120.2_playbook_remove_assets_from_policy.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and protectionStatus eq '{{ "{{ " }}protection_state{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'
          policy_name: '{{ "{{ " }}policy_name{{ " }}" }}'
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.k8s.wjt.namespace.remve.name }} WJT"
      workflow_job_template:
        name: "{{ ppdm.k8s.wjt.namespace.remove.name }}"
        inventory: "{{ awx.inventory[0].name }}"
        destroy_current_nodes: true
        workflow_nodes:
          - identifier: "{{ ppdm.k8s.jt.namespace.remove.name }}"
            unified_job_template:
              name: "{{ ppdm.k8s.jt.namespace.remove.name }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
        survey_enabled: true
        survey_spec: |        
          {
          "description": "Kubernetes Asset Offboaring Survey",
          "name": "Query_K8S",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "api.openshift.demo.local"
            ],
            "default": "api.openshift.demo.local",
            "required": true,
            "variable": "k8s_name",
            "new_question": false,
            "question_name": "Kubernetes Cluster",
            "question_description": ""
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "text",
                  "choices": "",
                  "default": "openshift-image-registry",
                  "required": true,
                  "variable": "namespace_name",
                  "new_question": false,
                  "question_name": "Kubernetes Namespace",
                  "question_description": "Enter the name of the Kubernetes Namespace"
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "text",
                  "choices": "",
                  "default": "default_policy",
                  "required": true,
                  "variable": "policy_name",
                  "new_question": false,
                  "question_name": "Protection Policy Name",
                  "question_description": "Enter the name of the Protection Policy"
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "multiplechoice",
                  "choices": [
                      "PROTECTED",
                      "DELETED"
                  ],
                  "default": "PROTECTED",
                  "required": true,
                  "variable": "protection_state",
                  "new_question": false,
                  "question_name": "Kubernetes Namespace",
                  "question_description": "Enter the name of the Kubernetes Namespace"
            }                        
          ]
          }
