---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename  
  tasks:
  - name: Create Kubeconfig Credentials
    credential_type: 
      name: kubeconfig
      description: Credential to use kube config file
      kind: cloud
      inputs: '{"fields":[{"id":"kubeconfig","type":"string","label":"KubeConfig","help_text":"Paste your KubeConfig"}]}'
      injectors: '{"env":{"K8S_AUTH_KUBECONFIG":"{{ "{{ " }}{{ filename }}{{ " }}" }}"},"file":{"template":"[mykubeconfig]\n{{ "{{ " }}kubeconfig{{ " }}" }}"}}'
      state: present
      validate_certs: false 