---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename 
  tasks:
    - name: "Add {{ ppdm.k8s.jt.add_ppdm_rbac  }}"
      job_template:
        name: "{{ ppdm.k8s.jt.add_ppdm_rbac  }}"
        description: Add / Update Kubernetes Cluster to PPDM with RBAC
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "130.1_playbook_rbac_add_k8s_to_ppdm.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
          - "openshift.demo.local"
        ask_credential_on_launch: true
        ask_variables_on_launch: true
        extra_vars:
          vcenter_server: vcenter01.demo.local
