---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename
  tasks:
    - name: Add {{ ppdm.k8s.wjt.asset_query }}
      workflow_job_template:
        name: "{{ ppdm.k8s.wjt.asset_query }}"
        inventory: "{{ awx.inventory[0].name }}"
        destroy_current_nodes: true
        workflow_nodes:
          - identifier: "{{ ppdm.k8s.wjt.asset_query }}"
            extra_data:
              asset_filter: name eq '"'{{ "{{ " }}namespace_name{{ " }}" }}'"' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '"'{{ "{{ " }}k8s_name{{ " }}" }}'"'
            unified_job_template:
              name: "{{ ppdm.assets.jt.query  }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
        survey_enabled: true
        survey_spec: |
          {
          "description": "Kubernetes Query Survey",
          "name": "Query_K8S",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "api.openshift.demo.local"
            ],
            "default": "api.openshift.demo.local",
            "required": true,
            "variable": "k8s_name",
            "new_question": false,
            "question_name": "Kubernetes Cluster",
            "question_description": ""
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "text",
                  "choices": "",
                  "default": "",
                  "required": true,
                  "variable": "namespace_name",
                  "new_question": false,
                  "question_name": "Kubernetes Namespace",
                  "question_description": "Enter the name of the Kubernetes Namespace"
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "multiplechoice",
                  "choices": [
                      "true",
                      "false"
                  ],
                  "default": "false",
                  "required": true,
                  "variable": "full_output",
                  "new_question": false,
                  "question_name": "DetailedOutput",
                  "question_description": "Display all Asset Details"
            }
          ]
          }
