---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename
  tasks:
    - name: "Give {{ ppdm.k8s.user_1.username }} WJT permissions"
      role:
        role: execute
        workflows:  ["{{ ppdm.k8s.wjt.namespace }}"]  
        user: "{{ ppdm.k8s.user_1.username }}"
        state: present

