---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename
  tasks:


    - name: "Add {{ ppdm.k8s.jt.plc.create }}"
      job_template:
        name: "{{ ppdm.k8s.jt.plc.create}}"
        description: Get K8S Policies
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "130.2_playbook_add_k8s_policy_v3.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
          - "{{ ppdd.credentials[0].name }}"
        extra_vars:
          k8s_policy_name: unique_name
          description: your_description
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: Add {{ ppdm.k8s.wjt.plc.create }}
      workflow_job_template:
        name: "{{ ppdm.k8s.wjt.plc.create }}"
        inventory: "{{ awx.inventory[0].name }}"
        destroy_current_nodes: true
        workflow_nodes:
          - identifier: "{{ ppdm.k8s.wjt.namespace.adhoc_protection }}"
            extra_data:
            unified_job_template:
              name: "{{ ppdm.k8s.jt.plc.create }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
        survey_enabled: true
        survey_spec: |
          {
          "description": "Kubernetes Policy Survey",
          "name": "Kubernetes Policy Name",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "api.openshift.demo.local"
            ],
            "default": "api.openshift.demo.local",
            "required": true,
            "variable": "k8s_name",
            "new_question": false,
            "question_name": "Kubernetes Cluster",
            "question_description": ""
            },
            {
                  "max": 64,
                  "min": 0,
                  "type": "text",
                  "choices": "",
                  "default": "",
                  "required": true,
                  "variable": "k8s_policy_name",
                  "new_question": false,
                  "question_name": "Kubernetes Namespace",
                  "question_description": "Enter the name of the Kubernetes Policy to create"
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "text",
                  "choices": "",
                  "default": "",
                  "required": true,
                  "variable": "decscription",
                  "new_question": false,
                  "question_name": "Description",
                  "question_description": "Enter the description of the Kubernetes Policy to create"
            }
          ]
          }

