---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename
  tasks:
    - name: Add PPDM Upgrade Workflow(s)
      workflow_job_template:
        destroy_current_nodes: true
        name: "{{ ppdm.infra.wjt.update_ppdm }}-{{ ppdm_index + 1 }}"
        inventory: "{{ awx.inventory[0].name }}"
        workflow_nodes:
          - identifier: "{{ ppdm.infra.jt.upload_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.upload_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.precheck_update }}"
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.precheck_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.precheck_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.approve_update }}"
              failure_nodes:
                - identifier: "{{ ppdm.infra.jt.update_history }}"
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.approve_update }}"
            all_parents_must_coverage: false
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.approve_update }}"
              timeout: 900
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: workflow_approval
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.execute_update }}"
              failure_nodes: []
              always_nodes: []
          - identifier: "{{ ppdm.infra.jt.execute_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.execute_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.update_history }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.update_history }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes:
                - identifier: "{{ ppdm.infra.jt.delete_update }}"
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.delete_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.delete_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
        survey_enabled: true        
        survey_spec: |        
          {
          "description": "Upgrade Survey",
          "name": "Upgrade_PPDM",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "19.18",
                "19.17",
                "19.16",
                "19.15"
            ],
            "default": "19.17",
            "required": true,
            "variable": "release",
            "new_question": false,
            "question_name": "PPDM Release",
            "question_description": "select the PPDM Release"
            },           
            {
            "max": 1024,
            "min": 0,
            "type": "text",
            "choices": "",
            "default": "dellemc-ppdm-upgrade-sw-19.17.0-18.pkg",
            "required": true,
            "variable": "package",
            "new_question": false,
            "question_name": "Package Name",
            "question_description": "Enter the name of the package, e.g. dellemc-ppdm-upgrade-sw-19.17.0-18.pkg"
            }                       
          ]
          }

      loop: "{{ ppdm.credentials }}"
      loop_control:
        index_var: ppdm_index
