---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - ansible.controller
    - awx.awx
  vars:
    filename: tower.filename
  tasks:
    - name: "Add {{ ppdm.k8s.jt.plc.get }}"
      job_template:
        name: "{{ ppdm.k8s.jt.plc.get }}"
        description: Get K8S Policies
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "110.0_get_protection_policies.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
        extra_vars:
          filter: assetType eq "KUBERNETES" # and name eq "{{ k8s_policy_name }}"
        ask_variables_on_launch: true
        ask_credential_on_launch: true
