# This example Playbook adds a Kubernetes Cluster to PPDM
# Kubernetes Information will be read from k8s core cluster_info module
# it is expected that Environment Variables are set for core K8S Modules
# e.g. export K8S_AUTH_KUBECONFIG= 
- name: Add K8S to PPDM
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  collections:
   - kubernetes.core     
  vars: 

  tasks:
  - debug:
      msg: "{{ lookup('env','K8S_AUTH_KUBECONFIG') }}"
    verbosity: 0      
  - name: Get Cluster information
    kubernetes.core.k8s_cluster_info:
#      verify_ssl: no
    register: api_status
  - debug: 
      msg: "Connected to {{ api_status }}"
      verbosity: 0