windows:    # <- a group of Hosts addressed as windows
  children:
    databasehosts:  # <- a group of Hosts addressed as databasehosts
      hosts:
        sql01: # <- an indivisual Host adressed as sql01
        sql02:
          ansible_host: sql02.demo.local # <- an indivisual Host adressed as sql02. resolvable as sql02.demo.local
      vars: # specific Vars for the Group Database Hosts
        app_agent: "{{ msapp_agent_windows }}"
        app_agent_product_id: '{165F48F4-38C4-49DF-904E-4A23D39078BF}'
    filehosts:
      hosts:
        file:
        launchpad:
          vars:
            ansible_winrm_scheme: http
      vars:
        app_agent: "{{ fs_agent_windows }}"
        app_agent_product_id: '{49C974B3-BA72-485C-9A96-794B065339DF}'
    exchangehosts:
      hosts:
        exchange1:
        exchange2:
      vars:
        app_agent: "{{ exchange_agent_windows }}"
        app_agent_product_id: '{165F48F4-38C4-49DF-904E-4A23D39078BF}'
  vars: # -> vars for all Windows Hosts
    ansible_user: administrator
    ansible_password: Password123!
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore
    ansible_shell_type: cmd
    ansible_connection: winrm
