- name: Start and stop VM´s
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:  
  - name: Look up VM´s in the inventory
    register: search_result
    vmware.vmware_rest.vcenter_vm_info:



  - set_fact: vmlist="{{ search_result.value  |  json_query(query) | json_query('[*].vm') }}"
    vars:
    #  query: "[?starts_with(name,'{{ item }}')]"    
      query: "[?match(name,'{{ item }}')]"            
    with_items: "{{ vm_names.split(',') }}" 

  - debug:
     msg: "{{ vmlist }}"


  - name: Starting VM´s
    register: vm_power
    vmware.vmware_rest.vcenter_vm_power:
      vm: "{{ item }}"
      state: "{{ state }}"
    with_items: "{{ vmlist }}" 
