- name: Start and stop VM´s
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:  
  - name: Look up VM´s in the inventory
    register: search_result
    vmware.vmware_rest.vcenter_vm_info:



  - set_fact: vmlist="{{ search_result.value  |  json_query(query) | json_query('[*].vm') }}"
    vars:
    #  query: "[?starts_with(name,'{{ item }}')]"    
      query: "[?contains(name,'{{ item }}')]"            
    with_items: "{{ vm_names.split(',') }}" 

  - debug:
     msg: "{{ vmlist }}"


  - name: Starting VM´s
    register: vm_power
    vmware.vmware_rest.vcenter_vm_power:
      vm: "{{ item }}"
      state: "{{ state }}"
    with_items: "{{ vmlist }}" 

  - name: Wait until my VM is ready
    vmware.vmware_rest.vcenter_vm_tools_info:
      vm: '{{ item }}'
    register: vm_tools_info
    until:
    - vm_tools_info is not failed
    - vm_tools_info.value.run_state == "RUNNING"
    retries: 60
    delay: 5 
    with_items: "{{ vmlist }}"
    when: state is defined and state == start
