- name: Start and stop VM´s
  hosts: localhost
  connection: local
  gather_facts: false
- tasks:  
  - name: Look up VM´s in the inventory
    register: search_result
    vmware.vmware_rest.vcenter_vm_info:
      filter_names:
      - sql03
      - sql04
