---
- name: AWX Role Based Access COntrol
  hosts: localhost
  connection: local
  collections:
    - ansible.controller
    - awx.awx
  tasks:
    - name: Job Template Permissions
      role_team_assignment:
        role_definition: 18
        object_id: 10
        team: App Team
        state: present
