---
- name: AWX Role Based Access COntrol
  hosts: localhost
  connection: local
  collections:
    - awx.awx
  tasks:
    - name: Job Template Permissions
      role_user_assignment:
        role_definition: 17
        object_id: 10
        team: Apps Team
        state: present
