---
- name: AWX Role Based Access COntrol
  hosts: localhost
  connection: local
  collections:
    - awx.awx
  tasks:
    - name: Job Template Permissions
      role_team_assignment:
        role_definition: 17
        object_id: 31
        team: App Team
        state: present
