apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: kubevirt-network-out
spec:
namespaceSelector:
  matchLabels:
    kubevirt-network-out: "true"
  network:
    topology: Localnet
    localnet:
      role: Secondary
      physicalNetworkName: physnet-kubevirt
      mtu: 1500
      ipam:
        mode: Disabled