apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: ddve-kubevirt-network
spec:
#  namespaceSelector:
#    matchLabels:
#      kubernetes.io/metadata.name: kubevirt
  network:
    topology: Localnet
    localnet:
      role: Secondary
      physicalNetworkName: physnet-kubevirt
      vlan:
        mode: Access
        access:
          id: 0
      mtu: 1500
      ipam:
        mode: Disabled