apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/operator-version: 2.19.1
    app.kubernetes.io/part-of: awx-prod
  name: awx-prod
  namespace: awx-operator
spec:
  web_readiness_timeout: 1
  postgres_keepalives_count: 5
  web_readiness_period: 0
  postgres_keepalives_idle: 5
  ee_resource_requirements:
    requests:
      cpu: 50m
      memory: 64M
  task_liveness_period: 0
  metrics_utility_cronjob_report_schedule: '@monthly'
  create_preload_data: false
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: true
  ingress_type: Route
  loadbalancer_port: 80
  web_liveness_failure_threshold: 3
  task_liveness_initial_delay: 5
  no_log: true
  task_readiness_failure_threshold: 3
  task_resource_requirements:
    requests:
      cpu: 50m
      memory: 128M
  image_pull_policy: IfNotPresent
  web_readiness_initial_delay: 20
  metrics_utility_console_enabled: false
  loadbalancer_ip: ''
  web_manage_replicas: true
  projects_storage_size: 8Gi
  auto_upgrade: true
  task_privileged: false
  task_readiness_period: 0
  web_liveness_timeout: 1
  postgres_keepalives: true
  task_readiness_timeout: 1
  web_liveness_period: 0
  metrics_utility_enabled: false
  postgres_keepalives_interval: 5
  ipv6_disabled: false
  task_liveness_failure_threshold: 3
  projects_storage_access_mode: ReadWriteMany
  metrics_utility_pvc_claim_size: 5Gi
  loadbalancer_class: ''
  set_self_labels: true
  web_resource_requirements:
    requests:
      cpu: 50m
      memory: 128M
  web_readiness_failure_threshold: 3
  web_liveness_initial_delay: 5
  task_readiness_initial_delay: 20
  projects_persistence: false
  task_manage_replicas: true
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  metrics_utility_cronjob_gather_schedule: '@hourly'
  task_liveness_timeout: 1
---
#kind: Secret
#apiVersion: v1
#metadata:
#  name: awx-prod-admin-password
#  namespace: awx-operator
#  labels:
#    app.kubernetes.io/component: awx
#    app.kubernetes.io/managed-by: awx-operator
#    app.kubernetes.io/operator-version: 2.19.0
#    app.kubernetes.io/part-of: awx-prod
#data:
#  password: UGFzc3dvcmQxMjMhCg== 
#  # password: ZVZjWHhUbWhpa0lyVk11enVGYUhYYkxzTzN4UUVCQW8=
#type: Opaque
