apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/awx-operator.awx-operator: ''  
  name: awx-operator
  namespace: awx-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: awx-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: awx-operator.v2.19.1




