apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/dell-csm-operator-certified.openshift-operators: ''  
  name: dell-csm-operator-certified
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: dell-csm-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: dell-csm-operator-certified.v1.4.3
