kind: Namespace
apiVersion: v1
metadata:
  name: minio-operator
  annotations:
    openshift.io/description: Minio Operator for S3 Storage
    openshift.io/display-name: Minio Operator
    openshift.io/node-selector: ''
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: MinIOJob.v1alpha1.job.min.io,PolicyBinding.v1alpha1.sts.min.io,Tenant.v2.minio.min.io
  generateName: minio-operator-
  generation: 1
  namespace: minio-operator
  resourceVersion: "3847130"
spec:
  upgradeStrategy: Default
status:
  namespaces:
  - ""
---
apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    generation: 1
    labels:
      operators.coreos.com/minio-operator.minio-operator: ""
    name: minio-operator
    namespace: minio-operator
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: minio-operator
    source: certified-operators
    sourceNamespace: openshift-marketplace
    startingCSV: minio-operator.v5.0.15

kind: List
metadata:
  resourceVersion: ""