---
- name: AWX Organization Deployment Runbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  vars:
    awx_filename_class: tower.filename
  collections:
    - ansible.controller
    - awx.awx
  tasks:
                
    - name: Set the TRACKING_STATE
      settings:
        settings:
          AUTH_LDAP_SERVER_URI: ldap://launchpad.demo.local:389
          AUTH_LDAP_BIND_DN: administrator@demo.local
          AUTH_LDAP_BIND_PASSWORD: Password123!
          AUTH_LDAP_START_TLS: false
          AUTH_LDAP_CONNECTION_OPTIONS:
            OPT_REFERRALS: 0
            OPT_NETWORK_TIMEOUT: 30
          AUTH_LDAP_USER_SEARCH:
          - DC=demo,DC=local
          - SCOPE_SUBTREE
          - "(userPrincipalName=%(user)s)"
          AUTH_LDAP_USER_DN_TEMPLATE: 
          AUTH_LDAP_USER_ATTR_MAP:
            email: mail
            last_name: sn
            first_name: givenName
          AUTH_LDAP_GROUP_SEARCH:
          - DC=demo,DC=local
          - SCOPE_SUBTREE
          - "(objectClass=group)"
          AUTH_LDAP_GROUP_TYPE: MemberDNGroupType
          AUTH_LDAP_GROUP_TYPE_PARAMS:
            name_attr: CN
            member_attr: member
          AUTH_LDAP_REQUIRE_GROUP: CN=AAP_USERS,CN=Users,DC=demo,DC=local
          AUTH_LDAP_DENY_GROUP: 
          AUTH_LDAP_USER_FLAGS_BY_GROUP:
            is_superuser:
            - CN=AAP_SUPERUSER,CN=Users,DC=demo,DC=local
          AUTH_LDAP_ORGANIZATION_MAP:
            Dell Org:
              users: CN=AAP_USERS,CN=Users,DC=demo,DC=local
              admins: CN=AAP_ADMIN_USERS,CN=Users,DC=demo,DC=local
              remove_admins: false
          AUTH_LDAP_TEAM_MAP:
            PPDM Infra Team:
              users: CN=AAP_INFRA_TEAM,CN=Users,DC=demo,DC=local
              remove: false
              organization: Dell Org
            Kubernetes Team:
              users: CN=AAP_K8S_TEAM,CN=Users,DC=demo,DC=local
              remove: false
              organization: Dell Org                          
            App Team:
              users: CN=AAP_APP_TEAM,CN=Users,DC=demo,DC=local
              remove: false
              organization: Dell Org 

    # - name: Set Subscription
    #   settings:
    #     settings:
    #       SUBSCRIPTIONS_USERNAME: "{{ lookup('env','SUBSCRIPTION_USERNAME') }}"
    #       SUBSCRIPTIONS_PASSWORD: "{{ lookup('env','SUBSCRIPTION_PASSWORD') }}"

 