---
- name: AWX Organiszation PPDM Update Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files:
    - ../vars/awx_vars.yaml

  collections:
    - ansible.controller
    - awx.awx
  tasks:
    - name: Add {{ ppdm.infra.label }} label to organization {{ awx.org }}
      label:
        name: "{{ ppdm.infra.label }}"
        organization: "{{ awx.org }}"
    - name: Create team {{ ppdm.infra.team.name }}
      team:
        name: "{{ ppdm.infra.team.name }}"
        description: "{{ ppdm.infra.team.description }}"
        organization: "{{ awx.org }}"
        state: present

    - name: Lookup {{ ppdm.infra.team.name }}
      set_fact:
        team: "{{ lookup('ansible.controller.controller_api', 'teams', query_params={ 'name': ppdm.infra.team.name  }) }}"

    - name: Add user to organization {{ awx.org }}
      user:
        username: "{{ ppdm.infra.user_1.username }}"
        password: "{{ ppdm.infra.user_1.password }}"
        email: "{{ ppdm.infra.user_1.email }}"
        organization: "{{ awx.org }}"
        state: present
        update_secrets: true

    - name: Give {{ ppdm.infra.user_1.username }} permissions
      role:
        role: member
        teams:
          -  "{{ team.id }}"
        user: "{{ ppdm.infra.user_1.username }}"
        state: present

    - name: "Add {{ ppdm.infra.jt.upload_update }}"
      job_template:
        name: "{{ ppdm.infra.jt.upload_update }}"
        description: Uploads the PPDM Update .pkg file from S3 to PPDM
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "9.9-playbook_upload_update_ppdm_from_s3.yml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.infra.jt.precheck_update }}"
      job_template:
        name: "{{ ppdm.infra.jt.precheck_update }}"
        description: Runs the Update Precheck
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "9.9-playbook_precheck_update_ppdm.yml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true

    - name: "Add Update {{ ppdm.infra.jt.execute_update }}"
      job_template:
        name: "{{ ppdm.infra.jt.execute_update }}"
        description: Runs the Update
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "9.9-playbook_install_update_ppdm.yml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.infra.jt.update_history }}"
      job_template:
        name: "{{ ppdm.infra.jt.update_history }}"
        description: Runs the Update
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "9.9-playbook_get_ppdm_update_package_history.yml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true

    - name: "Add {{ ppdm.infra.jt.delete_update }}"
      job_template:
        name: "{{ ppdm.infra.jt.delete_update }}"
        description: Runs the Update
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "9.9-playbook_delete_ppdm_update_package.yml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true

    - name: "Add Update {{ ppdm.infra.jt.execute_update }}"
      job_template:
        name: "{{ ppdm.infra.jt.execute_update }}"
        description: Runs the Update
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "9.9-playbook_install_update_ppdm.yml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true

    - name: Add PPDM Upgrade Workflow(s)
      workflow_job_template:
        destroy_current_nodes: true
        name: "{{ ppdm.infra.wjt.update_ppdm.name }}-{{ ppdm_index + 1 }}"
        inventory: "{{ awx.inventory[0].name }}"
        description: "{{ ppdm.infra.wjt.update_ppdm.description }}"
        workflow_nodes:
          - identifier: "{{ ppdm.infra.jt.upload_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.upload_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.precheck_update }}"
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.precheck_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.precheck_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.approve_update }}"
              failure_nodes:
                - identifier: "{{ ppdm.infra.jt.update_history }}"
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.approve_update }}"
            all_parents_must_coverage: false
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.approve_update }}"
              timeout: 900
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: workflow_approval
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.execute_update }}"
              failure_nodes:
                - identifier: "{{ ppdm.infra.jt.delete_update }}"
              always_nodes: []
          - identifier: "{{ ppdm.infra.jt.execute_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.execute_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.update_history }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.update_history }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes:
                - identifier: "{{ ppdm.infra.jt.delete_update }}"
              credentials:
                - name: "{{ item.name }}"
          - identifier: "{{ ppdm.infra.jt.delete_update }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.delete_update }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ item.name }}"
        survey_enabled: true        
        survey_spec: |        
          {
          "description": "Upgrade Survey",
          "name": "Upgrade_PPDM",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "19.18",
                "19.17",
                "19.16",
                "19.15"
            ],
            "default": "19.17",
            "required": true,
            "variable": "release",
            "new_question": false,
            "question_name": "PPDM Release",
            "question_description": "select the PPDM Release"
            },           
            {
            "max": 1024,
            "min": 0,
            "type": "text",
            "choices": "",
            "default": "dellemc-ppdm-upgrade-sw-19.17.0-18.pkg",
            "required": true,
            "variable": "package",
            "new_question": false,
            "question_name": "Package Name",
            "question_description": "Enter the name of the package, e.g. dellemc-ppdm-upgrade-sw-19.17.0-18.pkg"
            }                       
          ]
          }

      loop: "{{ ppdm.credentials }}"
      loop_control:
        index_var: ppdm_index


    - name: Give "{{ ppdm.infra.user_1.username }}" Execute WF Job Template permissions
      role:
        role: execute
        workflows: 
          - "{{ ppdm.infra.wjt.update_ppdm.name }}-{{ ppdm_index + 1 }}"
        user: "{{ ppdm.infra.user_1.username }}"
        state: present
      loop: "{{ ppdm.credentials }}"
      loop_control:
        index_var: ppdm_index

    - name: Give {{ ppdm.infra.user_1.username }} View  Job Template permissions
      role:
        role: read
        user: "{{ ppdm.infra.user_1.username }}"
        state: present
        job_templates:
          - "{{ ppdm.infra.jt.upload_update }}"
          - "{{ ppdm.infra.jt.execute_update }}"
          - "{{ ppdm.infra.jt.precheck_update }}"

    - name: Give {{ ppdm.infra.user_1.username }} Execute Job Template permissions
      role:
        role: execute
        user: "{{ ppdm.infra.user_1.username }}"
        state: present
        job_templates:
          - "{{ ppdm.infra.jt.update_history }}"
          - "{{ ppdm.infra.jt.delete_update }}"

    - name: Give {{ ppdm.infra.user_1.username }} Use Credentials  permissions
      role:
        role: use
        credentials: "{{ item.name }}"
        user: "{{ ppdm.infra.user_1.username }}"
        state: present
      loop: "{{ ppdm.credentials }}"
