---
- name: AWX Organiszation PPDM Update Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml

  collections:
    - awx.awx
  tasks:
 
  - name: Add {{ ppdm.infra.label }} label to organization {{ awx_org }}
    label:
      name: "{{ ppdm.infra.label }}"
      organization: "{{ awx_org }}"    
  - name: Create team {{ ppdm.infra.team.name }}
    team:
      name: "{{ ppdm.infra.team.name }}"
      description: "{{ ppdm.infra.team.description }}"
      organization: "{{ awx_org }}"
      state: present

  - name: Lookup {{ ppdm.infra.team.name }}  
    set_fact:
      team: "{{ lookup('awx.awx.controller_api', 'teams', query_params={ 'name': ppdm.infra.team.name  }) }}"


  - name: Add user to organization {{ awx_org }}
    user:
      username: "{{ ppdm.infra.user_1.username }}"
      password: "{{ ppdm.infra.user_1.password }}"
      email: "{{ ppdm.infra.user_1.email }}"
      organization: "{{ awx_org }}"
      state: present
      update_secrets: true

  - name: Give {{ ppdm.infra.user_1.username }} permissions
    role_user_assignment:
      role_definition: Team Member
      object_id: "{{ team.id }}"
      user: "{{ ppdm.infra.user_1.username }}"
      state: present

  - name: Add _9.1 Upload PPDM Update from S3
    job_template:
      name: _9.1 Upload PPDM Update from S3
      description: Uploads the PPDM Update .pkg file from S3 to PPDM
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm.project.name }}"
      playbook: "9.9-playbook_upload_update_ppdm_from_s3.yml"
      state: "present"
      labels:
        - "{{ ppdm.infra.label }}"
      credentials: [] 
      ask_credential_on_launch: true

  - name: Add _9.2 Precheck Update
    job_template:
      name: _9.2 Precheck Update
      description: Runs the Update Precheck
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm.project.name }}"
      playbook: "9.9-playbook_precheck_update_ppdm.yml"
      state: "present"
      labels:
        - "{{ ppdm.infra.label }}"
      credentials: []
      ask_credential_on_launch: true

  - name: Add _9.3 Update PPDM
    job_template:
      name: _9.3 Update PPDM
      description: Runs the Update
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm.project.name }}"
      playbook: "9.9-playbook_install_update_ppdm.yml"
      state: "present"
      labels:
        - "{{ ppdm.infra.label }}"
      credentials: []  
      ask_credential_on_launch: true   

  - name: Add _9.4 Update History
    job_template:
      name: _9.4 Update History
      description: Runs the Update
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm.project.name }}"
      playbook: "9.9-playbook_get_ppdm_update_package_history.yml"
      state: "present"
      labels:
        - "{{ ppdm.infra.label }}"
      credentials: [] 
      ask_credential_on_launch: true            

  - name: Add _9.9 Delete PPDM Update
    job_template:
      name: _9.9 Delete PPDM Update
      description: Runs the Update
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm.project.name }}"
      playbook: "9.9-playbook_delete_ppdm_update_package.yml"
      state: "present"
      labels:
        - "{{ ppdm.infra.label }}"
      credentials: []
      ask_credential_on_launch: true            

  
  - name: "{{ ppdm.infra.wjt.update }}"
      awx.awx.workflow_job_template:
      destroy_current_nodes: true    
      name: "{{ ppdm.infra.wjt.update }}"
      inventory: "{{ awx_inventory_1 }}"
      extra_vars: 
          package: dellemc-ppdm-upgrade-sw-19.17.0-10.pkg
          release: 19.17
      workflow_nodes:
        - identifier: "09-01-upload"
          extra_data: []
          unified_job_template:
            name: _9.1 Upload PPDM Update from S3
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: 
              - identifier: 09-02-precheck-update
            failure_nodes: []
            always_nodes: []
            credentials: 
                - name: "{{ ppdm.1.credentials }}"
        - identifier: 09-02-precheck-update
          extra_data: []
          unified_job_template:
            name: _9.2 Precheck Update
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: 
              - identifier: 09-03-approve-update
            failure_nodes: 
              - identifier: 09-04-update-history
            always_nodes: []
            credentials: 
                - name: "{{ ppdm.1.credentials }}"
        - identifier: "09-03-approve-update"
          all_parents_must_coverage: false	
          extra_data: []
          unified_job_template:
            name: _9.3 Approval for Update
            timeout: 900
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: workflow_approval
          related:
            success_nodes: 
              - identifier: 09-03-update-ppdm
            failure_nodes: []
            always_nodes: []
        - identifier: "09-03-update-ppdm"
          extra_data: []
          unified_job_template:
            name: _9.3 Update PPDM
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: 
                - name: "{{ ppdm.1.credentials }}"     
        - identifier: "09-04-update-history"
          extra_data: []
          unified_job_template:
            name: _9.4 Update History
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: 
              - identifier: 09-09-delete-update-package
            credentials: 
                - name: "{{ ppdm.1.credentials }}"         
        - identifier: "09-09-delete-update-package"
          extra_data: []
          unified_job_template:
            name: _9.9 Delete PPDM Update
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes:  []
            credentials: 
                - name: "{{ ppdm.1.credentials }}"


#  - name: Give {{ ppdmm.infra.user_1.username }} Job Template permissions
#    role_user_assignment:
#      role_definition: WorkflowJobTemplate Execute
#      object_id: "{{ lookup('awx.awx.controller_api', 'workflow_job_templates', query_params={ 'name': item  }).id }}"
#      user: "{{ ppdm.infra.user_1.username }}"
#      state: present
#    loop:
#      - "{{ ppdm.infra.wjt.update }}"