---
- name: AWX Organiszation Deployment Runbook
  hosts: localhost
  connection: local
  vars:
    awx_org: Dell Org
    awx_org_description: Dell DPS Org
    awx_app_team: App Team
    awx_app_team_description: Team handling all App Agent stuff
    awx_inventory_project: 0499
    awx_inventory_project_description: Base Inventory and Templates for 0499
    awc_inventory_url: https://github.com/bob-builds-labs/0499.git
  collections:
    - awx.awx
  tasks:
  - name: Create organization
    organization:
      name: "{{ awx_org }}"
      description: "{{ awx_org_description }}"
      state: present  
  - name: Create team
    team:
      name: "{{ awx_app_team }}"
      description: "{{ awx_app_team_description }}"
      organization: "{{ awx_org }}"
      state: present
  - name: Add Inventory Project
    project:
      name: "{{ awx_inventory_project }}"
      description: "{{ awx_inventory_project_description }}"
      organization: "{{ awx_org }}"
      scm_url: "{{ awc_inventory_url }}"
      scm_type: git
      state: present 
      timeout: 120
  - name: Update Inventory Project
    project_update:
      project: "{{ awx_inventory_project }}"
      timeout: 120
  - name: Add inventory
    inventory:
      name: "PPDM Inventory"
      description: "Our Foo Cloud Servers"
      organization: "{{ awx_org }}"
      state: present      
#  - name: Add an inventory source From Project
#    inventory_source:
#      name: "PPDM"
#      description: Source for inventory
#      inventory: previously-created-inventory
#      credential: previously-created-credential
#      overwrite: True
#      update_on_launch: True
#      organization: Default
#      source_vars:
#        private: false      
