---
- name: AWX Organiszation PPDM Update Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml

  collections:
    - awx.awx
  tasks:
 
  - name: Add {{ ppdm_infra_label }} label to organization {{ awx_org }}
    label:
      name: "{{ ppdm_infra_label }}"
      organization: "{{ awx_org }}"    
  - name: Create team {{ ppdm_infra_team }}
    team:
      name: "{{ ppdm_infra_team }}"
      description: "{{ ppdm_infra_team_description }}"
      organization: "{{ awx_org }}"
      state: present

  - name: Add PPDM1 Credentials
    credential:
      name: "{{ ppdm_1_credentials }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: "{{ ppdm_1_username }}"
        ppdm_password: "{{ ppdm_1_password }}"
        ppdm_fqdn: "{{ ppdm_1_fqdn }}"

  - name: Add PPDM2 Credentials
    credential:
      name: "{{ ppdm_2_credentials }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: "{{ ppdm_2_username }}"
        ppdm_password: "{{ ppdm_2_password }}"
        ppdm_fqdn: "{{ ppdm_2_fqdn }}"

  - name: Add _9.1 Upload PPDM Update from S3
    job_template:
      name: _9.1 Upload PPDM Update from S3
      description: Uploads the PPDM Update .pkg file from S3 to PPDM
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "9.9-playbook_upload_update_ppdm_from_s3.yml"
      state: "present"
      labels:
        - "{{ ppdm_infra_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}" 
      ask_credential_on_launch: true

  - name: Add _9.2 Precheck Update
    job_template:
      name: _9.2 Precheck Update
      description: Runs the Update Precheck
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "9.9-playbook_precheck_update_ppdm.yml"
      state: "present"
      labels:
        - "{{ ppdm_infra_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}" 
      ask_credential_on_launch: true

  - name: Add _9.3 Update PPDM
    job_template:
      name: _9.3 Update PPDM
      description: Runs the Update
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "9.9-playbook_install_update_ppdm.yml"
      state: "present"
      labels:
        - "{{ ppdm_infra_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}" 
      ask_credential_on_launch: true   

  - name: Add _9.4 Update History
    job_template:
      name: _9.4 Update History
      description: Runs the Update
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "9.9-playbook_get_ppdm_update_package_history.yml"
      state: "present"
      labels:
        - "{{ ppdm_infra_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}" 
      ask_credential_on_launch: true            

  - name: Add _9.9 Delete PPDM Update
    job_template:
      name: _9.9 Delete PPDM Update
      description: Runs the Update
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "9.9-playbook_delete_ppdm_update_package.yml"
      state: "present"
      labels:
        - "{{ ppdm_infra_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}" 
      ask_credential_on_launch: true            

  - name: 9 Update PPDM-1
    awx.awx.workflow_job_template:
      name: 9 Update PPDM-1
      inventory: "{{ awx_inventory_1 }}"
      extra_vars: "package: dellemc-ppdm-upgrade-sw-19.17.0-10.pkg\nrelease: 19.17"
      workflow_nodes:
        - identifier: "cd09857d-67f0-4c9a-83ec-f3952ac0ad50"
          extra_data: []
          unified_job_template:
            name: _9.2 Precheck Update
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: 
                - name: ppdm-1     