---
- name: AWX Role Based Access COntrol
  hosts: localhost
  connection: local
  vars:
    awx_org: Dell Org
    awx_org_description: Dell DPS Org
    awx_app_team: App Team
    awx_app_team_description: Team handling all App Agent stuff
    
  collections:
    - awx.awx
  tasks:
  - name: Create organization
    organization:
      name: "{{ awx_org }}"
      description: "{{ awx_org_description }}"
      state: present  
  - name: Create team
    team:
      name: "{{ awx_app_team }}"
      description: "{{ awx_app_team_description }}"
      organization: "{{ awx_org }}"
      state: present
