---
- name: AWX Organiszation Agent Templates Runbook
  hosts: localhost
  connection: local
  vars:
    awx_org: Dell Org
    awx_org_description: Dell DPS Org
    awx_app_team: App Team
    awx_app_team_description: Team handling all App Agent stuff
    awx_inventory_project: 0499
    awx_inventory_project_description: Base Inventory and Templates for 0499
    awx_inventory_url: https://github.com/bob-builds-labs/0499.git
    awx_inventory_source_1_description: Inventory vor Lab 1 Hosts
    awx_inventory_source_1: LAB1 Hosts
    awx_inventory_1: PPDM Inventory
    awx_inventory_1_description: PPDM Inventory for AWX
    awx_infra_label: awx_infra
    ppdm_agent_label: ppdm_agents
    ppdm_project: ansible_ppdm
    ppdm_release: 19.17
    ppdm_1_credentials: ppdm-1
  collections:
    - awx.awx
  tasks:
 
  - name: Add {{ ppdm_agent_label }} label to organization {{ awx_org }}
    label:
      name: "{{ ppdm_agent_label }}"
      organization: "{{ awx_org }}"    
  - name: Create team {{ awx_app_team }}
    team:
      name: "{{ awx_app_team }}"
      description: "{{ awx_app_team_description }}"
      organization: "{{ awx_org }}"
      state: present

  - name: Add PPDM1 Credentials
    credential:
      name: "{{ ppdm_1_credentials }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: admin
        ppdm_password: Password123!
        ppdm_fqdn: "ppdm-1.demo.local"
  - name: Add 100.0 List Agents from PPDM Job Template
    job_template:
      name: 100.0 List Agents from PPDM
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.0_list_agents.yml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"  
  - name: Add 100.1 Download Agents
    job_template:
      name: 100.1 Download Agents
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.1_download_agents_s3.yml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"        
      credentials:
        - "{{ ppdm_1_credentials }}" 
  - name: Add 100.2 Set DNS for Agents
    job_template:
      name: 100.2 Set DNS for Agents
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.2_set_dns_for_agents.yaml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"          
  - name: Add 100.3 Clear Hosts File for Windows Agents
    job_template:
      name: 100.3 Clear hosts file windows agent
      description: Delete wrong localhost entries
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.3_playbook_clear_hosts_windows_agent.yaml"
      state: "present"
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      labels:
        - "{{ ppdm_agent_label }}"
      limit: launchpad           

  - name: Add 100.3 Copy and Deploy Agents from S3
    job_template:
      name: 100.3 Copy and Deploy Agents from S3
      description: Copy and deploy PPDm Agents from S3 Storage
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.3_playbook_clear_hosts_windows_agent.yaml"
      extra_vars: 
        release: "{{ ppdm_release }}"
      ask_credential_on_launch: true
      ask_variables_on_launch: true
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"        

  - name: Add 100.4 Create Whitelist Entry from Address Query
    job_template:
      name: 100.4 Create Whitelist Entry from Address Query
      description: Approve Agents via Whitelist
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.3_playbook_clear_hosts_windows_agent.yaml"
      extra_vars: 
        host_list: launchpad.demo.local
      ask_credential_on_launch: true
      ask_variables_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"          