---
- name: AWX Organization PPDM Sysdr Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files:
    - ../vars/awx_vars.yaml
  collections:
    - ansible.controller
    - awx.awx
    - community.vmware
    - community.general
  tasks:
    - name: "Add {{ ppdm.infra.jt.reset_sysdr_boost }}"
      job_template:
        name: "{{ ppdm.infra.jt.reset_sysdr_boost }}"
        description: resets SysDR Password for Boost Unit
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdd.project.name }}"
        playbook: "3.2-Playbook-set-user-password.yml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true
        survey_enabled: true 
        extra_vars: {}
       


    - name: "Add {{ ppdm.infra.jt.sysdr_ppdm }}"
      job_template:
        name: "{{ ppdm.infra.jt.sysdr_ppdm }}"
        description: Runs PPDM SysDr
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "99.1-playbook_run_server_disaster_recovery.yaml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true
        survey_enabled: true 
        extra_vars: {}
        survey_spec: |        
          {
          "description": "SysDR Reset Survey",
          "name": "new Password",
          "spec": [                                
            {
            "max": 1024,
            "min": 0,
            "type": "text",
            "choices": "",
            "default": "Password123!",
            "required": true,
            "variable": "new_password",
            "new_question": false,
            "question_name": "new Password for His PPDM",
            "question_description": "Enter the name of the new SysDR Password"
            }
          ]
          }

    - name: "Add {{ ppdm.infra.jt.sysdr_ppdm_approved }}"
      job_template:
        name: "{{ ppdm.infra.jt.sysdr_ppdm_approved }}"
        description: Runs PPDM SysDr
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "99.1-playbook_run_server_disaster_recovery.yaml"
        state: "present"
        labels:
          - "{{ ppdm.infra.label }}"
        credentials: []
        ask_credential_on_launch: true
        survey_enabled: true 
        extra_vars: 
          auto_approve: true
        survey_spec: |        
          {
          "description": "SysDR Reset Survey",
          "name": "new Password",
          "spec": [                                
            {
            "max": 1024,
            "min": 0,
            "type": "text",
            "choices": "",
            "default": "Password123!",
            "required": true,
            "variable": "new_password",
            "new_question": false,
            "question_name": "new Password for His PPDM",
            "question_description": "Enter the name of the new SysDR Password"
            }
          ]
          }


    - name: Add PPDM ServerDisasterRecover Workflow(s)
      workflow_job_template:
        destroy_current_nodes: true
        name: "{{ ppdm.infra.wjt.sysdr_ppdm.name }}"
        inventory: "{{ awx.inventory[0].name }}"
        description: "{{ ppdm.infra.wjt.sysdr_ppdm.description }}"
        workflow_nodes:
          - identifier: "{{ ppdm.infra.jt.reset_sysdr_boost }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.reset_sysdr_boost }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: 
                - identifier: "{{ ppdm.infra.jt.sysdr_ppdm }}"
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ ppdm.credentials[0].name }}" 
                - name: "{{ ppdd.credentials[0].name }}"              
              ask_credential_on_launch: true
              survey_enabled: true   
          - identifier: "{{ ppdm.infra.jt.sysdr_ppdm }}"
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.sysdr_ppdm }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.approve_sysdr }}"
              failure_nodes: []
              always_nodes: []
              credentials:
                - name: "{{ ppdm.credentials[0].name }}" 
                - name: "{{ ppdd.credentials[0].name }}" 
              extra_vars: {}
              ask_credential_on_launch: true
              survey_enabled: true 
          - identifier: "{{ ppdm.infra.jt.approve_sysdr }}"
            all_parents_must_coverage: false
            extra_data: []
            unified_job_template:
              name: "{{ ppdm.infra.jt.approve_sysdr }}"
              timeout: 900
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: workflow_approval
            related:
              success_nodes:
                - identifier: "{{ ppdm.infra.jt.sysdr_ppdm_approved }}"
              failure_nodes: []
              always_nodes: []                            
        survey_enabled: true        
        survey_spec: |        
          {
          "description": "PPDM Deployment Survey",
          "name": "Deploy_PPDM",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "19.19",
                "19.18",
                "19.17",
                "19.16",
                "19.15"
            ],
            "default": "19.19",
            "required": true,
            "variable": "release",
            "new_question": false,
            "question_name": "PPDM Release",
            "question_description": "select the PPDM Release"
            },
            {
            "max": 1024,
            "min": 0,
            "type": "text",
            "choices": "",
            "default": "ppdm-1.demo.local",
            "required": true,
            "variable": "ppdm_fqdn",
            "new_question": false,
            "question_name": "Enter PPDM fqdn",
            "question_description": "Enter the FQDN of the PPDM do be deployed, e.g. ppdm-x.demo.local "
            },
            {
            "max": 1024,
            "min": 0,
            "type": "text",
            "choices": "",
            "default": "192.168.1.50",
            "required": true,
            "variable": "ppdm_ip",
            "new_question": false,
            "question_name": "Enter the IPv4 address of PPDM",
            "question_description": "Enter the IPv4 address of the PPDM do be deployed, e.g. 192.168.1.53"
            },
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "192.168.1.2"
            ],
            "default": "192.168.1.2",
            "required": true,
            "variable": "ppdm_gateway",
            "new_question": false,
            "question_name": "PPDM Gateway",
            "question_description": "select the PPDM IPv4 Gateway"
            },
            {  
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "192.168.1.2"
            ],
            "default": "192.168.1.2",
            "required": true,
            "variable": "ppdm_dns",
            "new_question": false,
            "question_name": "PPDM DNS",
            "question_description": "select the PPDM IPv4 DNS Server(s)"
            },   
            {  
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "255.255.255.0"
            ],
            "default": "255.255.255.0",
            "required": true,
            "variable": "ppdm_netmask",
            "new_question": false,
            "question_name": "PPDM Netmask",
            "question_description": "select the PPDM IPv4 netmask"
            },
            {  
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "true",
                "false"
            ],
            "default": "false",
            "required": true,
            "variable": "power_on",
            "new_question": false,
            "question_name": "Power On VM",
            "question_description": "should PPDM Powered on after Deployment ?"
            },
            {  
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "SysDR_ppdm-1",
                "SysDR_ppdm-2"
            ],
            "default": "SysDR_ppdm-1",
            "required": true,
            "variable": "user",
            "new_question": false,
            "question_name": "SysDR User",
            "question_description": "SysDR User for PPDM"
            }, 
            {
            "max": 1024,
            "min": 9,
            "type": "text",
            "choices": "",
            "default": "Tagist123!",
            "required": true,
            "variable": "new_password",
            "new_question": false,
            "question_name": "new Password for His PPDM",
            "question_description": "Enter the name of the new SysDR Password"
            },                                                          
            {
            "max": 1024,
            "min": 0,
            "type": "text",
            "choices": "",
            "default": "dellemc-ppdm-sw-19.19.0-1-20250225.044745-1269.ova",
            "required": true,
            "variable": "package",
            "new_question": false,
            "question_name": "Name of the OVA Template to deploy",
            "question_description": "Enter the name of the OVA File, e.g. dellemc-ppdm-sw-19.19.0-1-20250225.044745-1269.ova"
            }
          ]
          }


