---
- name: AWX Organiszation Assets Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml
  collections:
    - awx.awx
  tasks:
 
  - name: Add {{ ppdm_assets_label }} label to organization {{ awx_org }}
    label:
      name: "{{ ppdm_assets_label }}"
      organization: "{{ awx_org }}"    
  - name: Create team {{ awx_app_team }}
    team:
      name: "{{ awx_app_team }}"
      description: "{{ awx_app_team_description }}"
      organization: "{{ awx_org }}"
      state: present

  - name: Add PPDM1 Credentials
    credential:
      name: "{{ ppdm_1_credentials }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: "{{ ppdm_1_username }}"
        ppdm_password: "{{ ppdm_1_password }}"
        ppdm_fqdn: "{{ ppdm_1_fqdn }}"

  - name: Add PPDM2 Credentials
    credential:
      name: "{{ ppdm_2_credentials }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: "{{ ppdm_2_username }}"
        ppdm_password: "{{ ppdm_2_password }}"
        ppdm_fqdn: "{{ ppdm_2_fqdn }}"

  - name: Add 130.0 AdHoc Asset Protection
    job_template:
      name: 130.0 AdHoc Asset Protection
      description: AdHoc protection of Assets
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "130.0-playbook_start_asset_protection.yml"
      state: "present"
      labels:
        - "{{ ppdm_assets_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}" 
      extra_vars: 
        asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'
      ask_variables_on_launch: true
      ask_credential_on_launch: true

  - name: Add 30.0 Query Assets
    job_template:
      name: 30.0 Query Assets
      description: Query for Assets
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "30.0-playbook_get_assets.yml"
      state: "present"
      labels:
        - "{{ ppdm_assets_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}" 
      extra_vars: 
        asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'
      ask_variables_on_launch: true
      ask_credential_on_launch: true   

  - name: Add 130.0 AdHoc Protect K8S Asset
    awx.awx.workflow_job_template:
      name: 130.0 AdHoc Protect K8S Asset
      inventory: "{{ awx_inventory_1 }}"
      workflow_nodes:
        - identifier: e37d6788-e741-41c8-9b31-8ccf024ade69
          extra_data:
            asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'

          unified_job_template:
            name: 130.0 AdHoc Asset Protection
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []


  - name: Add 130.0 Query K8S Assets
    awx.awx.workflow_job_template:
      name: 130.0 Query K8S Assets
      inventory: "{{ awx_inventory_1 }}"
      destroy_current_nodes: true
      workflow_nodes:
        - identifier: 130.0-Query-K8S-Assets
          extra_data:
            asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'

          unified_job_template:
            name: 30.0 Query Assets
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []
      survey_enabled: true  
      survey_spec: |
              {
              "description": "Kubernetes Query Survey",
              "name": "Query_K8S",
              "spec": [
                {
                "max": 1024,
                "min": 0,
                "type": "multiplechoice",
                "choices": [
                    "api.openshift.demo.local"
                ],
                "default": "api.openshift.demo.local",
                "required": true,
                "variable": "k8s_name",
                "new_question": false,
                "question_name": "Kubernetes Cluster",
                "question_description": ""
                },
                {
                      "max": 1024,
                      "min": 0,
                      "type": "text",
                      "choices": "",
                      "default": "",
                      "required": true,
                      "variable": "namespace_name",
                      "new_question": false,
                      "question_name": "Kubernetes Namespace",
                      "question_description": "Enter the name of the Kubernetes Namespace"
                },
                {
                      "max": 1024,
                      "min": 0,
                      "type": "multiplechoice",
                      "choices": [
                          "true",
                          "false"
                      ],
                      "default": "false",
                      "required": true,
                      "variable": "full_output",
                      "new_question": false,
                      "question_name": "DetailedOutput",
                      "question_description": "Display all Asset Details"
                }
              ]
              }