---
- name: AWX Organization PPDM Deployment Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files:
    - ../vars/awx_vars.yaml

  collections:
    - ansible.controller
    - awx.awx
    - community.vmware
  tasks:


    - name: Give {{ ppdm.infra.user_1.username }} View  Job Template permissions
      role:
        role: read
        user: "{{ ppdm.infra.user_1.username }}"
        state: present
        job_templates:
          - "{{ ppdm.infra.jt.upload_update }}"
          - "{{ ppdm.infra.jt.execute_update }}"
          - "{{ ppdm.infra.jt.precheck_update }}"

    - name: Give {{ ppdm.infra.user_1.username }} Execute Job Template permissions
      role:
        role: execute
        user: "{{ ppdm.infra.user_1.username }}"
        state: present
        job_templates:
          - "{{ ppdm.infra.jt.update_history }}"
          - "{{ ppdm.infra.jt.delete_update }}"

    - name: Give {{ ppdm.infra.user_1.username }} Use Credentials  permissions
      role:
        role: use
        credentials: "{{ item.name }}"
        user: "{{ ppdm.infra.user_1.username }}"
        state: present
      loop: "{{ ppdm.credentials }}"
