---
- name: AWX Organiszation Agent Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml

  collections:
    - ansible.controller
    - awx.awx
  tasks:
 
  - name: Add {{ ppdm.agents.label }} label to organization {{ awx.org }}
    label:
      name: "{{ ppdm.agents.label }}"
      organization: "{{ awx.org }}"    
  - name: Create team {{ ppdm.agents.team.name }}
    team:
      name: "{{ ppdm.agents.team.name }}"
      description: "{{ ppdm.agents.team.description }}"
      organization: "{{ awx.org }}"
      state: present
    register: result   

  - name: Lookup {{ ppdm.agents.team.name }}  
    set_fact:
      team: "{{ lookup('ansible.controller.controller_api', 'teams', query_params={ 'name': ppdm.agents.team.name  }) }}"


  - name: Add user to organization {{ awx.org }}
    user:
      username: "{{ ppdm.agents.user_1.username }}"
      password: "{{ ppdm.agents.user_1.password }}"
      email: "{{ ppdm.agents.user_1.email }}"
      organization: "{{ awx.org }}"
      state: present
      update_secrets: true


  - name: Give {{ ppdm.agents.user_1.username }} permissions
    role:
      role: member
#      object_ansible_id: "{{ team.summary_fields.resource.ansible_id | int }}"
      teams: 
        - "{{ team.id }}"
      user: "{{ ppdm.agents.user_1.username }}"
      state: present



  - name: "Add {{ ppdm.agents.jt.list }} Job Template"
    job_template:
      name: "{{ ppdm.agents.jt.list }}"
      job_type: "run"
      organization: "{{ awx.org }}"
      inventory: "{{ awx.inventory[0].name }}"
      project: "{{ ppdm.project.name }}"
      playbook: "100.0_list_agents.yml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm.agents.label }}"
      credentials:
        - "{{ ppdm.credentials[0].name }}"  
  - name: "Add {{ ppdm.agents.jt.download }}"
    job_template:
      name: "{{ ppdm.agents.jt.download }}"
      job_type: "run"
      organization: "{{ awx.org }}"
      inventory: "{{ awx.inventory[0].name }}"
      project: "{{ ppdm.project.name }}"
      playbook: "100.1_download_agents_s3.yml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm.agents.label }}"        
      credentials:
        - "{{ ppdm.credentials[0].name }}" 
  - name: "Add {{ ppdm.agents.jt.set_dns}}"
    job_template:
      name: "{{ ppdm.agents.jt.set_dns}}"
      job_type: "run"
      organization: "{{ awx.org }}"
      inventory: "{{ awx.inventory[0].name }}"
      project: "{{ ppdm.project.name }}"
      playbook: "100.2_set_dns_for_agents.yaml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm.agents.label }}"
      credentials:
        - "{{ ppdm.credentials[0].name }}"          
  - name: "Add {{ ppdm.agents.jt.clear_hosts }}"
    job_template:
      name: "{{ ppdm.agents.jt.clear_hosts }}"
      description: Delete wrong localhost entries
      job_type: "run"
      organization: "{{ awx.org }}"
      inventory: "{{ awx.inventory[0].name }}"
      project: "{{ ppdm.project.name }}"
      playbook: "100.3_playbook_clear_hosts_windows_agent.yaml"
      state: "present"
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      labels:
        - "{{ ppdm.agents.label }}"
      limit: launchpad           

  - name: "Add {{ ppdm.agents.jt.deploy }}"
    job_template:
      name: "{{ ppdm.agents.jt.deploy }}"
      description: Copy and deploy PPDM Agents from S3 Storage
      job_type: "run"
      organization: "{{ awx.org }}"
      inventory: "{{ awx.inventory[0].name }}"
      project: "{{ ppdm.project.name }}"
      playbook: "100.3_playbook_copy_and_deploy_windows_agent_s3.yaml"
      extra_vars: 
        release: "{{ ppdm.release }}"
      ask_credential_on_launch: true
      ask_variables_on_launch: true
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm.agents.label }}"
      credentials:
        - "{{ ppdm.credentials[0].name }}"        

  - name: "Add {{ ppdm.agents.jt.approve }}"
    job_template:
      name: "{{ ppdm.agents.jt.approve }}"
      description: Approve Agents via Whitelist
      job_type: "run"
      organization: "{{ awx.org }}"
      inventory: "{{ awx.inventory[0].name }}"
      project: "{{ ppdm.project.name }}"
      playbook: "100.4_create_whitelistentry_from_addressquery.yaml"
      extra_vars: 
        host_list: launchpad.demo.local
      ask_credential_on_launch: true
      ask_variables_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm.agents.label }}"
      credentials:
        - "{{ ppdm.credentials[0].name }}"

  - name: "Add {{ ppdm.agents.jt.uninstall }}"
    job_template:
      name: "{{ ppdm.agents.jt.uninstall }}"
      description: Remove Windows Agent
      job_type: "run"
      organization: "{{ awx.org }}"
      inventory: "{{ awx.inventory[0].name }}"
      project: "{{ ppdm.project.name }}"
      playbook: "100.9_playbook-uninstall-windows_agent_s3.yaml"
      extra_vars: 
        release: "{{ ppdm.release }}"
      ask_variables_on_launch: true
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm.agents.label }}"
      credentials:
        - "{{ ppdm.credentials[0].name }}"                   

  - name: "Give {{ ppdm.agents.user_1.username }} permissions"
    role:
      user: "{{ ppdm.agents.user_1.username }}"    
      role: execute
      job_templates:
        - "{{ ppdm.agents.jt.list }}"
        - "{{ ppdm.agents.jt.download }}"
        - "{{ ppdm.agents.jt.approve }}"
        - "{{ ppdm.agents.jt.set_dns }}"
        - "{{ ppdm.agents.jt.clear_hosts }}"
        - "{{ ppdm.agents.jt.deploy }}"
        - "{{ ppdm.agents.jt.uninstall }}"      
      state: present


