---
- name: AWX Organiszation Deployment Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - awx.awx
  tasks:
  - name: Set the value of awx settings ANSIBLE_JINJA2_NATIVE
    settings:
      name: AWX_TASK_ENV  
      value: '{"ANSIBLE_JINJA2_NATIVE": "True"}'
    register: result 
    until: result.failed is defined and result.failed == false
    retries: 10
    delay: 10

  - debug: 
      msg: "{{ result }}"
      verbosity: 1
  - name: Set the Custom Login Info
    settings:
      name: CUSTOM_LOGIN_INFO  
      value: "{{ awx_custom_login_info }}"

  - name: Set the Custom Logo
    settings:
      name: CUSTOM_LOGO  
      value: "{{ custom_logo }}"
  
  - name: Create organization {{ awx_org }}
    organization:
      name: "{{ awx_org }}"
      description: "{{ awx_org_description }}"
      state: present
  - name: Add Ansible Galaxy Credentials
    credential:
      name: "{{ awx_galaxy_credentials_name }}"
      credential_type: Ansible Galaxy/Automation Hub API Token
      organization: "{{ awx_org }}"
      inputs:
        url: "https://galaxy.ansible.com" 

  - name: Add Galaxy Credentials to organization {{ awx_org }}
    organization:
      name: "{{ awx_org }}"
      galaxy_credentials: "{{ awx_galaxy_credentials_name }}"
      description: "{{ awx_org_description }}"
      state: present

  - name: Add {{ awx_infra_label }} label to organization {{ awx_org }}
    label:
      name: "{{ awx_infra_label }}"
      organization: "{{ awx_org }}"
         
  - name: Create PPDM Credential Type
    credential_type:
      name: Dell PPDM Credentials
      description: Credential to log into PowerProtect Datamanager
      kind: cloud
      inputs: {"fields":[{"id":"ppdm_fqdn","type":"string","label":"PPDM FQDN","help_text":"Enter the fqdn or IP address that corresponds to your PPDM Instance"},{"id":"ppdm_username","type":"string","label":"Username"},{"id":"ppdm_password","type":"string","label":"Password","secret":true}],"required":["ppdm_fqdn","ppdm_username","ppdm_password"]}
      injectors: {'env':{'PPDM_FQDN':'{{ "{{ " }}ppdm_fqdn{{ " }}" }}' ,'PPDM_PASSWORD':'{{ "{{ " }}ppdm_password{{ " }}" }}','PPDM_USERNAME':'{{ "{{ " }}ppdm_username{{ " }}" }}','PPDM_INITIAL_PASSWORD':'{{ "{{ " }}ppdm_password{{ " }}" }}'}}
      state: present
      validate_certs: false 
  - name: Add PPDM1 Credentials
    credential:
      name: "{{ ppdm.1.credentials }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: "{{ ppdm.1.username }}"
        ppdm_password: "{{ ppdm.1.password }}"
        ppdm_fqdn: "{{ ppdm.1.fqdn }}"

  - name: Add PPDM2 Credentials
    credential:
      name: "{{ ppdm.2.credentials }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: "{{ ppdm.2.username }}"
        ppdm_password: "{{ ppdm.2.password }}"
        ppdm_fqdn: "{{ ppdm.2.fqdn }}"
  - name: Create AWX Credential Type
    credential_type:
      name: AWX Credentials
      description: Credential to log into AWX
      kind: cloud
      inputs: {"fields":[{"id":"awx_host","type":"string","label":"AWX HOST","help_text":"Enter the fqdn or IP address that corresponds to your AWX Instance"},{"id":"awx_username","type":"string","label":"Username"},{"id":"awx_password","type":"string","label":"Password","secret":true}],"required":["awx_fqdn","awx_username","awx_password"]}
      injectors: {'env':{'CONTROLLER_HOST':'{{ "{{ " }}awx_host{{ " }}" }}' ,'CONTROLLER_PASSWORD':'{{ "{{ " }}awx_password{{ " }}" }}','CONTROLLER_USERNAME':'{{ "{{ " }}awx_username{{ " }}" }}','CONTROLLER_VERIFY_SSL':'false'}}
      state: present
      validate_certs: false

  - name: Create team {{ awx_app_team }}
    team:
      name: "{{ awx_app_team }}"
      description: "{{ awx_app_team_description }}"
      organization: "{{ awx_org }}"
      state: present

  - name: Add {{ ppdm.project.name }} Project from {{ ppdm.project.modules_url }}
    project:
      name: "{{ ppdm.project.name }}"
      description: "{{ ppdm.project.description  }}"
      organization: "{{ awx_org }}"
      scm_url: "{{ ppdm.project.modules_url }}"
      scm_type: git
      state: present 
      timeout: 600

  - name: Update Modules Project {{ ppdm.project.name }} 
    project_update:
      project:  "{{ ppdm.project.name }}"
      timeout: 600 

  - name: Add Inventory Project {{ awx_inventory_project }}
    project:
      name: "{{ awx_inventory_project }}"
      description: "{{ awx_inventory_project_description }}"
      organization: "{{ awx_org }}"
      scm_url: "{{ awx_inventory_url }}"
      scm_type: git
      state: present 
      timeout: 120
      scm_update_on_launch: true

  - name: Update Inventory Project {{ awx_inventory_project }}
    project_update:
      project: "{{ awx_inventory_project }}"
      timeout: 600

  - name: Add inventory {{ awx_inventory_1 }}
    inventory:
      name: "{{ awx_inventory_1 }}"
      description: "{{ awx_inventory_1_description }}"
      organization: "{{ awx_org }}"
      state: present  

  - name: Add inventory source {{ awx_inventory_source_1 }} from Project {{ awx_inventory_project }}
    inventory_source:
      name: "{{ awx_inventory_source_1 }}"
      description: "{{ awx_inventory_source_1_description }}"
      inventory: "{{ awx_inventory_1 }}"
      organization: "{{ awx_org }}"
      source: scm
      source_path: lab1/hosts.yaml
      source_project: "{{ awx_inventory_project }}"
      source_vars:
      state: present

  - name: Update inventory source {{ awx_inventory_source_1 }}
    inventory_source_update:
      name: "{{ awx_inventory_source_1 }}"
      inventory: "{{ awx_inventory_1 }}"
      organization: "{{ awx_org }}"

  - name: Add AWX Admin Credentials
    credential:
      name: AWX Admin Credentials
      credential_type: AWX Credentials
      organization: "{{ awx_org }}"
      inputs:
        awx_username: "{{ lookup('env','CONTROLLER_USERNAME') }}"
        awx_password: "{{ lookup('env','CONTROLLER_PASSWORD') }}"
        awx_host: "{{ lookup('env','CONTROLLER_HOST') }}"

  - name: Add Ansible Galaxy Credentials
    credential:
      name: Ansible Galaxy
      credential_type: Ansible Galaxy/Automation Hub API Token
      organization: "{{ awx_org }}"
      inputs:
        url: "https://galaxy.ansible.com" 




  - name: Create AWX deployment Job Template
    job_template:
      name: "{{ awx_infra_job_template }}"
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ awx_inventory_project }}"
      playbook: "playbooks/awx_awx.yaml"
      credentials:
        - "AWX Admin Credentials"
      state: "present"
      labels:
        - "{{ awx_infra_label }}"



  - name: Create PPDM Agents Job Templates
    job_template:
      name: "{{ ppdm.agents.job_template }}"
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ awx_inventory_project }}"
      playbook: "playbooks/awx_ppdm_agents_templates.yaml"
      credentials:
        - "AWX Admin Credentials"
      state: "present"
      labels:
        - "{{ awx_infra_label }}"    
#  - name: Launch PPDM Agent Jobs Deployment
#    job_launch:
#      job_template: "{{ ppdm.agents.job_template }}"   

  - name: Create PPDM Assets Job Templates
    job_template:
      name: "{{ ppdm.assets.job_template }}"
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ awx_inventory_project }}"
      playbook: "playbooks/awx_ppdm_assets_templates.yaml"
      credentials:
        - "AWX Admin Credentials"
      state: "present"
      labels:
        - "{{ awx_infra_label }}"  

  - name: Create PPDM update Job Templates
    job_template:
      name: "{{ ppdm.infra.update_job_template }}"
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ awx_inventory_project }}"
      playbook: "playbooks/awx_ppdm_update_templates.yaml"
      credentials:
        - "AWX Admin Credentials"
      state: "present"
      labels:
        - "{{ awx_infra_label }}"  

  - name: Create PPDM K8S Job Templates
    job_template:
      name: "{{ ppdm.k8s.job_template }}"
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ awx_inventory_project }}"
      playbook: "playbooks/awx_ppdm_k8s_templates.yaml"
      credentials:
        - "AWX Admin Credentials"
      state: "present"
      labels:
        - "{{ awx_infra_label }}"

  - name: Create Minio Instance Job
    job_template:
      name: "deploy minio to ansible host"
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ awx_inventory_project }}"
      playbook: "playbooks/awx_awx_minio.yaml"
      credentials:
#       - "AWX Admin Credentials"
      state: "present"
      labels:
        - "{{ awx_infra_label }}"
      limit: ansible



  
  
  - name: AWX PPDM template Maintain Workflow
    awx.awx.workflow_job_template:
      destroy_current_nodes: true    
      name: "{{ awx_infra_workflow_job_template }}"
      inventory: "{{ awx_inventory_1 }}"
      description: "Automated AWX Update workflow for PPDM Automation"
      workflow_nodes:
        - identifier: "0_{{ awx_infra_job_template }}"
          extra_data: []
          unified_job_template:
            name: "{{ awx_infra_job_template }}"
            description: "Automated AWX Infrustructure Update"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: 
              - identifier: "0_{{ ppdm.agents.job_template }}" 
              - identifier: "0_{{ ppdm.assets.job_template }}" 
              - identifier: "0_{{ ppdm.infra.update_job_template }}" 
            failure_nodes: []
            always_nodes: []
            credentials: []      
        - identifier: "0_{{ ppdm.agents.job_template }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.agents.job_template }}"
            description: "Automated Update of Agent Job Templates"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []
        - identifier: "0_{{ ppdm.assets.job_template }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.assets.job_template }}"
            description: "Automated Update of Asset Job Templates"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []            

        - identifier: "0_{{ ppdm.infra.update_job_template }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.infra.update_job_template }}"
            description: "Automated Update of Update Job Templates"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []            

  - name: Build a schedule for AWX Template
    schedule:
      name: "awx schedule"
      state: present
      unified_job_template: "{{ awx_infra_workflow_job_template }}"
      rrule: "DTSTART:20191219T230551Z RRULE:FREQ=DAILY;INTERVAL=1"