---
- name: AWX Organiszation Deployment Runbook
  hosts: localhost
  connection: local
  vars:
    awx_org: Dell Org
    awx_org_description: Dell DPS Org
    awx_app_team: App Team
    awx_app_team_description: Team handling all App Agent stuff
    awx_inventory_project: 0499
    awx_inventory_project_description: Base Inventory and Templates for 0499
    awx_inventory_url: https://github.com/bob-builds-labs/0499.git
    awx_inventory_source_1_description: Inventory vor Lab 1 Hosts
    awx_inventory_source_1: LAB1 Hosts
    awx_inventory_1: PPDM Inventory
    awx_inventory_1_description: PPDM Inventory for AWX
  collections:
    - awx.awx
  tasks:
  - name: Create organization
    organization:
      name: "{{ awx_org }}"
      description: "{{ awx_org_description }}"
      state: present
  - credential_type:
      name: Dell PPDM Credentials
      description: Credential to log into PowerProtect Datamanager
      kind: cloud
      inputs: {"fields":[{"id":"ppdm_fqdn","type":"string","label":"PPDM FQDN","help_text":"Enter the fqdn or IP address that corresponds to your PPDM Instance"},{"id":"ppdm_username","type":"string","label":"Username"},{"id":"ppdm_password","type":"string","label":"Password","secret":true}],"required":["ppdm_fqdn","ppdm_username","ppdm_password"]}
      injectors: {'env':{'PPDM_FQDN':'{{ ppdm_fqdn }}','PPDM_PASSWORD':'\{\{ ppdm_password \}\}','PPDM_USERNAME':'\{\{ ppdm_username \}\}','PPDM_INITIAL_PASSWORD':'\{\{ ppdm_password \}\}'}}
      state: present
      validate_certs: false      
  - name: Create team
    team:
      name: "{{ awx_app_team }}"
      description: "{{ awx_app_team_description }}"
      organization: "{{ awx_org }}"
      state: present
  - name: Add Inventory Project
    project:
      name: "{{ awx_inventory_project }}"
      description: "{{ awx_inventory_project_description }}"
      organization: "{{ awx_org }}"
      scm_url: "{{ awx_inventory_url }}"
      scm_type: git
      state: present 
      timeout: 120
  - name: Update Inventory Project
    project_update:
      project: "{{ awx_inventory_project }}"
      timeout: 120
  - name: Add inventory
    inventory:
      name: "{{ awx_inventory_1 }}"
      description: "{{ awx_inventory_1_description }}"
      organization: "{{ awx_org }}"
      state: present      
  - name: Add an inventory source From Project
    inventory_source:
      name: "{{ awx_inventory_source_1 }}"
      description: "{{ awx_inventory_source_1_description }}"
      inventory: "{{ awx_inventory_1 }}"
      organization: "{{ awx_org }}"
      source: scm
      source_path: lab1/hosts.yaml
      source_project: "{{ awx_inventory_project }}"
      source_vars:
      state: present
  - name: Update  inventory source
    inventory_source_update:
      name: "{{ awx_inventory_source_1 }}"
      inventory: "{{ awx_inventory_1 }}"
      organization: "{{ awx_org }}"

