---
- name: AWX Organiszation Kubernetes Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml

  collections:
    - awx.awx
  tasks:
 
  - name: Add {{ ppdm.k8s.label }} label to organization {{ awx_org }}
    label:
      name: "{{ ppdm.k8s.label }}"
      organization: "{{ awx_org }}"    
  - name: Create team {{ ppdm.k8s.team }}
    team:
      name: "{{ ppdm.k8s.team }}"
      description: "{{ ppdm.k8s.team_description }}"
      organization: "{{ awx_org }}"
      state: present
    register: result   

  - name: Lookup {{ ppdm.k8s.team }}  
    set_fact:
      team: "{{ lookup('awx.awx.controller_api', 'teams', query_params={ 'name': ppdm.k8s.team  }) }}"


  - name: Add user to organization {{ awx_org }}
    user:
      username: "{{ ppdm.k8s.user_1.username }}"
      password: "{{ ppdm.k8s.user_1.password }}"
      email: "{{ ppdm.k8s.user_1.email }}"
      organization: "{{ awx_org }}"
      state: present
      update_secrets: true


  - name: Give {{ ppdmm.k8s.user_1.username }} permissions
    role_user_assignment:
      role_definition: Team Member
#      object_ansible_id: "{{ team.summary_fields.resource.ansible_id | int }}"
      object_id: "{{ team.id }}"
      user: "{{ ppdm.k8s.user_1.username }}"
      state: present


  - name: Add {{ ppdm.k8s.wjt.asset_protection }}
    awx.awx.workflow_job_template:
      name: "{{ ppdm.k8s.wjt.asset_protection }}"
      inventory: "{{ awx_inventory_1 }}"
      destroy_current_nodes: true
      workflow_nodes:
        - identifier: "{{ ppdm.k8s.wjt.asset_protection }}"
          extra_data:
            asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'

          unified_job_template:
            name: 130.0 AdHoc Asset Protection
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []

#  - name: Lookup {{ ppdm.k8s.wjt.asset_protection }}  
#    set_fact:
#      wjt: "{{ lookup('awx.awx.controller_api', 'workflow_job_templates', query_params={ 'name': ppdm.k8s.wjt.asset_protection  }).id }}"







  - name: Add {{ ppdm.k8s.wjt.asset_query }}
    awx.awx.workflow_job_template:
      name: "{{ ppdm.k8s.wjt.asset_query }}"
      inventory: "{{ awx_inventory_1 }}"
      destroy_current_nodes: true
      workflow_nodes:
        - identifier: "{{ ppdm.k8s.wjt.asset_query }}"
          extra_data:
            asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'
          unified_job_template:
            name: 30.0 Query Assets
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []
      survey_enabled: true  
      survey_spec: |
              {
              "description": "Kubernetes Query Survey",
              "name": "Query_K8S",
              "spec": [
                {
                "max": 1024,
                "min": 0,
                "type": "multiplechoice",
                "choices": [
                    "api.openshift.demo.local"
                ],
                "default": "api.openshift.demo.local",
                "required": true,
                "variable": "k8s_name",
                "new_question": false,
                "question_name": "Kubernetes Cluster",
                "question_description": ""
                },
                {
                      "max": 1024,
                      "min": 0,
                      "type": "text",
                      "choices": "",
                      "default": "",
                      "required": true,
                      "variable": "namespace_name",
                      "new_question": false,
                      "question_name": "Kubernetes Namespace",
                      "question_description": "Enter the name of the Kubernetes Namespace"
                },
                {
                      "max": 1024,
                      "min": 0,
                      "type": "multiplechoice",
                      "choices": [
                          "true",
                          "false"
                      ],
                      "default": "false",
                      "required": true,
                      "variable": "full_output",
                      "new_question": false,
                      "question_name": "DetailedOutput",
                      "question_description": "Display all Asset Details"
                }
              ]
              }

  - name: Give {{ ppdmm.k8s.user_1.username }} permissions
    role_user_assignment:
      role_definition: WorkflowJobTemplate Execute
      object_id: "{{ lookup('awx.awx.controller_api', 'workflow_job_templates', query_params={ 'name': item  }).id }}"
      user: "{{ ppdm.k8s.user_1.username }}"
      state: present
    loop:
     - "{{ ppdm.k8s.wjt.asset_protection }}"
     - "{{ ppdm.k8s.wjt.wjt.asset_query }}"
