---
- name: AWX Organiszation Agent Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml

  collections:
    - awx.awx
  tasks:
 
  - name: Add {{ ppdm_agent_label }} label to organization {{ awx_org }}
    label:
      name: "{{ ppdm_agent_label }}"
      organization: "{{ awx_org }}"    
  - name: Create team {{ awx_app_team }}
    team:
      name: "{{ awx_app_team }}"
      description: "{{ awx_app_team_description }}"
      organization: "{{ awx_org }}"
      state: present

  - name: Add 100.0 List Agents from PPDM Job Template
    job_template:
      name: 100.0 List Agents from PPDM
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.0_list_agents.yml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"  
  - name: Add 100.1 Download Agents
    job_template:
      name: 100.1 Download Agents
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.1_download_agents_s3.yml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"        
      credentials:
        - "{{ ppdm_1_credentials }}" 
  - name: Add 100.2 Set DNS for Agents
    job_template:
      name: 100.2 Set DNS for Agents
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.2_set_dns_for_agents.yaml"
      ask_credential_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"          
  - name: Add 100.3 Clear Hosts File for Windows Agents
    job_template:
      name: 100.3 Clear hosts file windows agent
      description: Delete wrong localhost entries
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.3_playbook_clear_hosts_windows_agent.yaml"
      state: "present"
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      labels:
        - "{{ ppdm_agent_label }}"
      limit: launchpad           

  - name: Add 100.3 Copy and Deploy Agents from S3
    job_template:
      name: 100.3 Copy and Deploy Agents from S3
      description: Copy and deploy PPDM Agents from S3 Storage
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.3_playbook_copy_and_deploy_windows_agent_s3.yaml"
      extra_vars: 
        release: "{{ ppdm_release }}"
      ask_credential_on_launch: true
      ask_variables_on_launch: true
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"        

  - name: Add 100.4 Create Whitelist Entry from Address Query
    job_template:
      name: 100.4 Create Whitelist Entry from Address Query
      description: Approve Agents via Whitelist
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.4_create_whitelistentry_from_addressquery.yaml"
      extra_vars: 
        host_list: launchpad.demo.local
      ask_credential_on_launch: true
      ask_variables_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"

  - name: Add 100.9 Uninstall Windows Agent
    job_template:
      name: 100.9 Uninstall Windows Agent
      description: Remove Windows Agent
      job_type: "run"
      organization: "{{ awx_org }}"
      inventory: "{{ awx_inventory_1 }}"
      project: "{{ ppdm_project }}"
      playbook: "100.9_playbook-uninstall-windows_agent_s3.yaml"
      extra_vars: 
        release: "{{ ppdm_release }}"
      ask_variables_on_launch: true
      ask_inventory_on_launch: true
      ask_limit_on_launch: true
      state: "present"
      labels:
        - "{{ ppdm_agent_label }}"
      credentials:
        - "{{ ppdm_1_credentials }}"                   