---
- name: AWX Organization Kubernetes Templates Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files:
    - ../vars/awx_vars.yaml

  collections:
    - ansible.controller
    - awx.awx
  tasks:
    - name: Add {{ ppdm.k8s.label }} label to organization {{ awx.org }}
      label:
        name: "{{ ppdm.k8s.label }}"
        organization: "{{ awx.org }}"
    - name: Create team {{ ppdm.k8s.team }}
      team:
        name: "{{ ppdm.k8s.team }}"
        description: "{{ ppdm.k8s.team_description }}"
        organization: "{{ awx.org }}"
        state: present
      register: result

    - name: Lookup {{ ppdm.k8s.team }}
      set_fact:
        team: "{{ lookup('ansible.controller.controller_api', 'teams', query_params={ 'name': ppdm.k8s.team  }) }}"

    - name: Add user to organization {{ awx.org }}
      user:
        username: "{{ ppdm.k8s.user_1.username }}"
        password: "{{ ppdm.k8s.user_1.password }}"
        email: "{{ ppdm.k8s.user_1.email }}"
        organization: "{{ awx.org }}"
        state: present
        update_secrets: true

    - name: Give {{ ppdm.k8s.user_1.username }} permissions
      role:
        role: member
        teams:
         - "{{ team.id }}"
        user: "{{ ppdm.k8s.user_1.username }}"
        state: present

    - name: Add {{ ppdm.k8s.wjt.asset_protection }}
      workflow_job_template:
        name: "{{ ppdm.k8s.wjt.asset_protection }}"
        inventory: "{{ awx.inventory[0].name }}"
        destroy_current_nodes: true
        workflow_nodes:
          - identifier: "{{ ppdm.k8s.wjt.asset_protection }}"
            extra_data:
              asset_filter: name eq '{{ "{{ " }}namespace_name{{ " }}" }}' and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq '{{ "{{ " }}k8s_name{{ " }}" }}'
            unified_job_template:
              name: "{{ ppdm.assets.jt.adhoc_protection  }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
        survey_enabled: true
        survey_spec: |
          {
          "description": "Kubernetes Query Survey",
          "name": "Query_K8S",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "api.openshift.demo.local"
            ],
            "default": "api.openshift.demo.local",
            "required": true,
            "variable": "k8s_name",
            "new_question": false,
            "question_name": "Kubernetes Cluster",
            "question_description": ""
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "text",
                  "choices": "",
                  "default": "",
                  "required": true,
                  "variable": "namespace_name",
                  "new_question": false,
                  "question_name": "Kubernetes Namespace",
                  "question_description": "Enter the name of the Kubernetes Namespace"
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "multiplechoice",
                  "choices": [
                      "true",
                      "false"
                  ],
                  "default": "false",
                  "required": true,
                  "variable": "full_output",
                  "new_question": false,
                  "question_name": "DetailedOutput",
                  "question_description": "Display all Asset Details"
            }
          ]
          }

    - name: Add {{ ppdm.k8s.wjt.asset_state_query }}
      workflow_job_template:
        name: "{{ ppdm.k8s.wjt.asset_state_query }}"
        inventory: "{{ awx.inventory[0].name }}"
        destroy_current_nodes: true
        workflow_nodes:
          - identifier: "{{ ppdm.k8s.wjt.asset_protection }}"
            extra_data:
              asset_filter: type eq "KUBERNETES" and protectionStatus eq "'{{ "{{ " }}protection_state{{ " }}" }}'" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq "'{{ "{{ " }}k8s_name{{ " }}" }}'" 
            unified_job_template:
              name: "{{ ppdm.assets.jt.query  }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
        survey_enabled: true
        survey_spec: |
          {
          "description": "Kubernetes Asset Protection Survey",
          "name": "Query_K8S",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "api.openshift.demo.local"
            ],
            "default": "api.openshift.demo.local",
            "required": true,
            "variable": "k8s_name",
            "new_question": false,
            "question_name": "Kubernetes Cluster",
            "question_description": ""
            },
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "PROTECTED",
                "UNPROTECTED"
            ],
            "default": "PROTECTED",
            "required": true,
            "variable": "protection_state",
            "new_question": false,
            "question_name": "Protection State",
            "question_description": "State of the Namespace"
            }            
          ]
          }






    #  - name: Lookup {{ ppdm.k8s.wjt.asset_protection }}
    #    set_fact:
    #      wjt: "{{ lookup('ansible.controller.controller_api', 'workflow_job_templates', query_params={ 'name': ppdm.k8s.wjt.asset_protection  }).id }}"

    - name: Add {{ ppdm.k8s.wjt.asset_query }}
      workflow_job_template:
        name: "{{ ppdm.k8s.wjt.asset_query }}"
        inventory: "{{ awx.inventory[0].name }}"
        destroy_current_nodes: true
        workflow_nodes:
          - identifier: "{{ ppdm.k8s.wjt.asset_query }}"
            extra_data:
              asset_filter: name eq "{{ "{{ " }}namespace_name{{ " }}" }}" and type eq "KUBERNETES" and subtype eq "K8S_NAMESPACE" and details.k8s.inventorySourceName eq "{{ "{{ " }}k8s_name{{ " }}" }}"
            unified_job_template:
              name: "{{ ppdm.assets.jt.query  }}"
              inventory:
                organization:
                  name: "{{ awx.org }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
        survey_enabled: true
        survey_spec: |
          {
          "description": "Kubernetes Query Survey",
          "name": "Query_K8S",
          "spec": [
            {
            "max": 1024,
            "min": 0,
            "type": "multiplechoice",
            "choices": [
                "api.openshift.demo.local"
            ],
            "default": "api.openshift.demo.local",
            "required": true,
            "variable": "k8s_name",
            "new_question": false,
            "question_name": "Kubernetes Cluster",
            "question_description": ""
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "text",
                  "choices": "",
                  "default": "",
                  "required": true,
                  "variable": "namespace_name",
                  "new_question": false,
                  "question_name": "Kubernetes Namespace",
                  "question_description": "Enter the name of the Kubernetes Namespace"
            },
            {
                  "max": 1024,
                  "min": 0,
                  "type": "multiplechoice",
                  "choices": [
                      "true",
                      "false"
                  ],
                  "default": "false",
                  "required": true,
                  "variable": "full_output",
                  "new_question": false,
                  "question_name": "DetailedOutput",
                  "question_description": "Display all Asset Details"
            }
          ]
          }

    - name: "Add {{ ppdm.k8s.jt.add_ppdm_rbac  }}"
      job_template:
        name: "{{ ppdm.k8s.jt.add_ppdm_rbac  }}"
        description: Add / Update Kubernetes Cluster to PPDM with RBAC
        job_type: "run"
        organization: "{{ awx.org }}"
        inventory: "{{ awx.inventory[0].name }}"
        project: "{{ ppdm.project.name }}"
        playbook: "130.1_playbook_rbac_add_k8s_to_ppdm.yaml"
        state: "present"
        labels:
          - "{{ ppdm.assets.label }}"
        credentials:
          - "{{ ppdm.credentials[0].name }}"
          - "openshift.demo.local"
        ask_credential_on_launch: true
        ask_variables_on_launch: true
        extra_vars:
          vcenter_server: vcenter01.demo.local

    - name: "Give {{ ppdm.k8s.user_1.username }} WJT permissions"
      role:
        role: execute
        workflows:
        - "{{ ppdm.k8s.wjt.asset_protection }}"
        - "{{ ppdm.k8s.wjt.asset_query }}"
        - "{{ ppdm.k8s.wjt.asset_state_query }}"        
        user: "{{ ppdm.k8s.user_1.username }}"
        state: present



    - name: "Give {{ ppdm.k8s.user_1.username }} JT Read permissions"
      role:
        role: read        
        user: "{{ ppdm.k8s.user_1.username }}"
        state: present
        job_templates:
        - "{{ ppdm.assets.jt.query  }}"
        - "{{ ppdm.assets.jt.adhoc_protection  }}"



    - name: "Give {{ ppdm.k8s.user_1.username }} JT Execute permissions"
      role:
        role: execute        
        user: "{{ ppdm.k8s.user_1.username }}"
        state: present
        job_templates:
        - "{{ ppdm.k8s.jt.add_ppdm_rbac  }}"
