
- name: Deploy PPDM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ova: /home/admin/Downloads/
  tasks:

  

- community.vmware.vmware_deploy_ovf:
  #  hostname: '{{ vcenter_hostname }}'
  #  username: '{{ vcenter_username }}'
  #  password: '{{ vcenter_password }}'
    datacenter: democenter
    cluster: cluster
    datastore: nfs-datastore
    name: ppdm-3
    networks: "{u'VM Network':u'VLAN0 prod vm network'}"
    power_on: false
    inject_ovf_env: true
    properties: 
      vami.ip0.brs: 192.168.1.53 
      vami.gateway.brs: 192.168.1.2
      vami.netmask0.brs: 255.255.255.0
      vami.DNS.brs:  192.168.1.2
      vami.fqdn.brs: ppdm-2.demo.local
    ovf: "{{ ova }}"
  delegate_to: localhost
