---
- name: AWX Organiszation Deployment Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - awx.awx
  tasks:

  - name: debug1
    debug:
      msg: "{{ lookup('awx.awx.controller_api', 'workflow_job_templates', query_params={ 'name': ( ppdm.infra.wjt.update_ppdm ~ '-1' )  }) }}"
      verbosity: 0
    loop: "{{ ppdm.credentials }}"
    loop_control:
      index_var: ppdm_index      
  
  - name: Give {{ ppdmm.infra.user_1.username }} Execute WF Job Template permissions
    role_user_assignment:
      role_definition: WorkflowJobTemplate Execute
      object_id: "{{ lookup('awx.awx.controller_api', 'workflow_job_templates', query_params={ 'name': ( ppdm.infra.wjt.update_ppdm ~ '-' ~ (ppdm_index + 1) )  }).id }}"
      user: "{{ ppdm.infra.user_1.username }}"
      state: present
    loop: "{{ ppdm.credentials }}"
    loop_control:
      index_var: ppdm_index

  - name: Give {{ ppdmm.infra.user_1.username }} Use Credentials  permissions
    role_user_assignment:
      role_definition: Credential Use
      object_id: "{{ lookup('awx.awx.controller_api', 'credentials', query_params={ 'name': item.name  }).id }}"
      user: "{{ ppdm.infra.user_1.username }}"
      state: present
    loop: "{{ ppdm.credentials }}"
