---
- name: AWX Organiszation Deployment Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - awx.awx
  tasks:
  
  - name: Add PPDM Credentials
    credential:
      name: "{{ item.name }}"
      credential_type: Dell PPDM Credentials
      organization: "{{ awx_org }}"
      inputs:
        ppdm_username: "{{ item.username }}"
        ppdm_password: "{{ item.password }}"
        ppdm_fqdn: "{{ item.fqdn }}"
    loop: "{{ ppdm.credentials }}"