---
- name: AWX Organiszation Deployment Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - awx.awx
  tasks:
  
  - name: Add PPDM Upgrade Workflow(s)
    awx.awx.workflow_job_template:
      destroy_current_nodes: true    
      name: "{{ ppdm.infra.wjt.update_ppdm }}-{{ ppdm_index + 1 }}"
      inventory: "{{ awx_inventory_1 }}"
      extra_vars: 
          package: dellemc-ppdm-upgrade-sw-19.17.0-10.pkg
          release: 19.17
      workflow_nodes:
        - identifier: "{{ ppdm.infra.jt.upload_update }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.infra.jt.upload_update }}"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: 
              - identifier: "{{ ppdm.infra.jt.precheck_update }}"
            failure_nodes: []
            always_nodes: []
            credentials: 
                - name: "{{ item.name }}" 
        - identifier: "{{ ppdm.infra.jt.precheck_update }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.infra.jt.precheck_update }}"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: 
              - identifier: "{{ ppdm.infra.jt.approve_update }}"
            failure_nodes: 
              - identifier: "{{ ppdm.infra.jt.update_history }}"
            always_nodes: []
            credentials: 
                - name: "{{ item.name }}" 
        - identifier: "{{ ppdm.infra.jt.approve_update }}"
          all_parents_must_coverage: false	
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.infra.jt.approve_update }}"
            timeout: 900
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: workflow_approval
          related:
            success_nodes: 
              - identifier: "{{ ppdm.infra.jt.execute_update }}"
            failure_nodes: []
            always_nodes: []
        - identifier: "{{ ppdm.infra.jt.execute_update }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.infra.jt.execute_update }}"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: 
                - name: "{{ item.namee }}"     
        - identifier: "{{ ppdm.infra.jt.update_history }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.infra.jt.update_history }}"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: 
              - identifier: "{{ ppdm.infra.jt.delete_update }}"
            credentials: 
                - name: "{{ item.name }}"         
        - identifier: "{{ ppdm.infra.jt.delete_update }}"
          extra_data: []
          unified_job_template:
            name: "{{ ppdm.infra.jt.delete_update }}"
            inventory:
              organization:
                name: "{{ awx_org }}"
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes:  []
            credentials: 
                - name: "{{ item.name }}"         
    loop: "{{ ppdm.credentials }}"
    loop_control:
      index_var: ppdm_index      
