---
- name: AWX Organiszation Deployment Runbook
  hosts: localhost
  connection: local
  vars:
  vars_files: 
    - ../vars/awx_vars.yaml
    - ../vars/logo_var.yaml
  collections:
    - awx.awx
  tasks:

  - name: Add Inventory Project {{ awx.inventory[0].project_name  }}
    project:
      name: "{{ awx.inventory[0].project_name  }}"
      description: "{{ awx.inventory[0].scm_description }}"
      organization: "{{ awx.org }}"
      scm_url: "{{ awx.inventory[0].scm_url }}"
      scm_branch: "{{ awx.inventory[0].scm_branch }}"
      scm_type: git
      state: present 
      timeout: 120
      scm_update_on_launch: true

  - name: Add inventory source {{ awx.inventory[0].source[0].name }} from Project {{ awx.inventory[0].project_name  }}
    inventory_source:
      name: "{{ awx.inventory[0].source[0].name }}"
      description: "{{ awx.inventory[0].source[0].description }}"
      inventory: "{{ awx.inventory[0].name }}"
      organization: "{{ awx.org }}"
      source: scm
      source_path: lab1/hosts.yaml
      source_project: "{{ awx.inventory[0].project_name  }}"
      source_vars:
      state: present
