---
- name: Deploy Minio for ansible in Bob Lab
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    minio_group: minio
    minio_user: minio
    datapath: /home/minio
    ansible_become_password: Password123!
    download_url: https://dl.minio.io/server/minio/release/linux-amd64/minio.deb
    minio_user: minioadmnin
    minio_password: Password123!
  tasks:
  - name: "Get the Minio server checksum"
    set_fact:
      checksum: "{{ lookup('url', 'https://dl.minio.io/server/minio/release/linux-amd64/minio.sha256sum').split(' ')[0] }}"

  - name: Create Minio group 
    group:
      name: "{{ minio_group }}"
      state: present
    become: true

  - name: Create Minio user
    user:
      name: "{{ minio_user }}"
      group: "{{ minio_group }}"
      system: "yes"
      shell: "/usr/sbin/nologin"
    become: true

  - name: Create the Minio data storage directories
    file:
      path: "{{ datapath }}"
      state: directory
      owner: "{{ minio_user }}"
      group: "{{ minio_group }}"
      mode: 0777
    become: true

  - name: Download the Minio server
    get_url:
      url: "{{ download_url }}"
      dest: "/tmp"
      mode: 0755
      # checksum: "sha256:{{ checksum }}"
    register: download
    until: download is succeeded
    retries: 5
    delay: 2
    become: true
  - name: Create the Minio Config File
    template:
      content: |
        MINIO_ROOT_USER="{{ minio_user }}"
        MINIO_ROOT_PASSWORD="{{ minio_password }}"
        MINIO_VOLUMES=/home/minio
        MINIO_OPTS="--console-address :9090"

      dest: "/etc/default/minio"
      owner: "root"
      group: "root"
  - name: Install Minio
    apt:
      deb: /tmp/minio.deb
    become: true

#  - name: Generate the Minio server envfile
#    template:
#      src: minio.env.j2
#      dest: "{{ minio_server_envfile }}"
#      owner: "root"
#      group: "{{ minio_group }}"
#      mode: 0640
#    notify: restart minio

 # - name: Create the Minio server systemd config
 #   template:
 #     src: minio.service.j2
 #     dest: "/etc/systemd/system/minio.service"
 #     owner: "root"
 #     group: "root"
 #   when: ansible_service_mgr == "systemd"


  - name: Enable and start the Minio service
    service:
      name: minio
      state: restart
      enabled: true