
- name: Portgroups
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:  
  - name: Get the dvswitch 
    vmware.vmware_rest.vcenter_network_info:
      filter_types: DISTRIBUTED_PORTGROUP
      filter_names: storage + backup 
    register: my_portgroup

  - name: Collect a list of the NIC for a given VM
    vmware.vmware_rest.vcenter_vm_hardware_ethernet_info:
      vm: '{{ test_vm1_info.id }}'
    register: vm_nic
